### ISSUE TITLE
Issue with incorrect utterance start labels in dev set

### ISSUE THREAD

**Issue by medbar** [microsoft/NOTSOFAR1-Challenge#43]
Dear organizers,

I am a participant in the notsofar-1 competition and I have identified an outlier in the dev dataset. Specifically, MTG_30522 (S30522107) contains incorrect start labels for speech utterances. These labels were recorded using a close-range microphone, which is not permitted for competition use. The signal from the device mc_plaza_0 is shifted more than 15 seconds compared to the close-range microphone close_talk/CT_22 . The first utterance in the annotation starts at 23 seconds, while in the recording on the mc_plaza_0 device it starts at 8 seconds.

I am bringing this to your attention in hopes of resolving this issue to maintain fairness and accuracy in the competition. Thank you for your prompt attention to this matter.

**Comment by nidleo** [comment]
Thanks for reporting this! Indeed we are aware that MTG_30522 is misaligned with some of the close-talk microphones and GT annotation timestamps. According to our tests it seems to be an isolated issue to meeting 'MTG-30522'.

A few notes:
1. Since it's too late to update the datasets and we want all participants to use the same version, when reporting your dev-set performance, please use it as is, including the erroneous meeting. For internal testing, you are welcome to fix or exclude this meeting.
2. Please recall that NOTSOFAR follows the same rules as DASR which state that the dev-set is not allowed for training.

**Comment by medbar** [comment]
Yea, we use the dev-set-2 only to evaluate our system. 
If this issue occurs in only one session of the dev-set-2, then it is not a significant concern. We will fix it in our internal tests. 

Thank you for your response!
